source 'http://rubygems.org'

gem 'nokogiri'
gem 'open-uri'
gem 'open_uri_redirections'
gem 'rest-client'
gem 'food2fork'
gem 'html_to_plain_text'
gem 'Pry'
gem 'HTTParty'
gem 'JSON'
gem 'csv'
gem 'rubygems'
gem 'terminal-table/import'
gem 'paint'